### ISSUE TITLE
Enable issues at jenkinsci/jenkins-publish-over-cifs-plugin

### ISSUE THREAD

**Issue by simonschmeisser** [bap2000/jenkins-publish-over-cifs-plugin#2]
I know this is a strange way of communication but I don't know of a better one:

@slide could you please open/add the issues feature over at https://github.com/jenkinsci/publish-over-cifs-plugin ? Version 0.6 stalls at when it tries to copy files and I don't know where to report and discuss this

https://help.github.com/articles/disabling-issues/ explains the reverse operation

**Comment by slide** [comment]
You file issues on the Jenkins JIRA at https://issues.jenkins-ci.org. The issue with 0.6 is a known issue and has already been filed and a fix is underway. Jenkins projects don't use Github issues.

**Comment by simonschmeisser** [comment]
thanks didn't know that. There is no info about jira on the plugin site, might want to add some?

Cool that there is a fix already!

**Comment by slide** [comment]
It's a general Jenkins thing, not specific to each plugin. https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue
